# Generated by Django 3.0.3 on 2020-02-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('maplink', models.CharField(blank=True, max_length=500, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='docs')),
                ('file2', models.FileField(blank=True, null=True, upload_to='docs')),
                ('file3', models.FileField(blank=True, null=True, upload_to='docs')),
                ('file4', models.FileField(blank=True, null=True, upload_to='docs')),
                ('file5', models.FileField(blank=True, null=True, upload_to='docs')),
                ('file6', models.FileField(blank=True, null=True, upload_to='docs')),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
    ]
