# Generated by Django 3.0.3 on 2020-02-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='body_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='title_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='body_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='body_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
