# Generated by Django 3.0.3 on 2020-02-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200209_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='mapdraw',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
