# Generated by Django 3.0.3 on 2020-02-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_offer_mapdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
    ]
