# Generated by Django 3.0.3 on 2020-02-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pageitem_pageskin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageitem',
            name='about_intro_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='about_intro_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='about_intro_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='aboutus_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='aboutus_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='aboutus_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='contact_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='contact_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='contact_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='cookie_alert_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='cookie_alert_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='cookie_alert_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='credit_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='credit_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='credit_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='design_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='design_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='design_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='gallery_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='gallery_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='gallery_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='headtitle_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='headtitle_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='headtitle_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='lang_flag_en',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='lang_flag_pl',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='lang_flag_ru',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='location_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='location_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='location_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='main_intro_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='main_intro_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='main_intro_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='mainpage_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='mainpage_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='mainpage_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='management_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='management_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='management_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='offer_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='offer_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='offer_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='remodelling_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='remodelling_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='remodelling_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='save_time_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='save_time_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageitem',
            name='save_time_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
