# Generated by Django 3.0.3 on 2020-02-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200209_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageitem',
            name='credit_en',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='credit_pl',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='credit_ru',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='design_en',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='design_pl',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='design_ru',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='management_en',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='management_pl',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='management_ru',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='remodelling_en',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='remodelling_pl',
        ),
        migrations.RemoveField(
            model_name='pageitem',
            name='remodelling_ru',
        ),
    ]
